# Generated by Django 6.0.2 on 2026-04-17 03:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_alter_membership_unique_together_flag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('network_extraction', 'Pore Network Extraction'), ('permeability', 'Permeability Calculation'), ('morphology', 'Morphological Analysis'), ('visualization', '3D Visualization'), ('full_suite', 'Complete Analysis Suite')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID', max_length=100, null=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0, help_text='Job completion percentage')),
                ('error_message', models.TextField(blank=True, help_text='Error details if job failed')),
                ('estimated_cost', models.DecimalField(decimal_places=2, help_text='Estimated cost in USD', max_digits=8)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost charged', max_digits=8, null=True)),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='started_jobs', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Analysis Job',
                'verbose_name_plural': 'Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network_file', models.FileField(blank=True, help_text='Extracted pore network file', null=True, upload_to='analysis_results/')),
                ('visualization_file', models.FileField(blank=True, help_text='3D visualization file', null=True, upload_to='analysis_results/')),
                ('report_file', models.FileField(blank=True, help_text='Analysis report PDF', null=True, upload_to='analysis_results/')),
                ('metrics', models.JSONField(default=dict, help_text='Analysis metrics and properties')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='pore_analysis.analysisjob')),
            ],
            options={
                'verbose_name': 'Analysis Result',
                'verbose_name_plural': 'Analysis Results',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Credit Purchase'), ('usage', 'Analysis Usage'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in USD (positive=credit, negative=debit)', max_digits=8)),
                ('description', models.CharField(help_text='Description of the transaction', max_length=200)),
                ('stripe_charge_id', models.CharField(blank=True, help_text='Stripe charge ID for purchases', max_length=100, null=True)),
                ('analysis_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='pore_analysis.analysisjob')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-provided name for the image', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the image')),
                ('file', models.FileField(help_text='The .npy file containing the boolean array', upload_to='uploaded_images/')),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('dimensions', models.JSONField(help_text='Array shape as [x, y, z]')),
                ('voxel_size', models.FloatField(blank=True, help_text='Voxel size in micrometers', null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Image',
                'verbose_name_plural': 'Uploaded Images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_jobs', to='pore_analysis.uploadedimage'),
        ),
    ]
