# Generated by Django 6.0.2 on 2026-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Generated thumbnail image', null=True, upload_to='image_thumbnails/'),
        ),
    ]
