# Generated by Django 6.0.2 on 2026-04-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0002_uploadedimage_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='metrics',
            field=models.JSONField(blank=True, default=dict, help_text='Image metrics'),
        ),
    ]
