# Generated by Django 6.0.2 on 2026-04-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0003_uploadedimage_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Submitted analysis parameters'),
        ),
    ]
