# Generated by Django 6.0.2 on 2026-04-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0004_analysisjob_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='analysis_type',
            field=models.CharField(choices=[('network_extraction', 'Pore Network Extraction'), ('permeability', 'Permeability Calculation'), ('diffusivity', 'Diffusivity Calculation'), ('morphology', 'Morphological Analysis'), ('visualization', '3D Visualization'), ('full_suite', 'Complete Analysis Suite')], max_length=50),
        ),
    ]
