# Generated by Django 6.0.2 on 2026-04-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0005_add_diffusivity_analysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='analysis_type',
            field=models.CharField(choices=[('network_extraction', 'Pore Network Extraction'), ('network_validation', 'Network Validation'), ('permeability', 'Permeability Calculation'), ('diffusivity', 'Diffusivity Calculation'), ('morphology', 'Morphological Analysis'), ('visualization', '3D Visualization'), ('poresize', 'Pore Size Distribution'), ('full_suite', 'Complete Analysis Suite')], max_length=50),
        ),
    ]
