# Generated by Django 6.0.2 on 2026-04-20 15:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0006_alter_analysisjob_analysis_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisjob',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual credits charged', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, help_text='Estimated credits for this job', max_digits=8),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Credit amount (positive=credit, negative=debit)', max_digits=8),
        ),
        migrations.CreateModel(
            name='AnalysisPricingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis_type', models.CharField(choices=[('network_extraction', 'Pore Network Extraction'), ('network_validation', 'Network Validation'), ('permeability', 'Permeability Calculation'), ('diffusivity', 'Diffusivity Calculation'), ('morphology', 'Morphological Analysis'), ('visualization', '3D Visualization'), ('poresize', 'Pore Size Distribution'), ('full_suite', 'Complete Analysis Suite')], max_length=50)),
                ('backend', models.CharField(default='default', help_text='Compute backend key (e.g. cpu, gpu, default)', max_length=20)),
                ('credits_per_million_voxels', models.DecimalField(decimal_places=4, help_text='Credits charged per one million voxels', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Analysis Pricing Rate',
                'verbose_name_plural': 'Analysis Pricing Rates',
                'ordering': ['analysis_type', 'backend'],
                'constraints': [models.UniqueConstraint(fields=('analysis_type', 'backend'), name='unique_analysis_pricing_rate')],
            },
        ),
    ]
