# Generated by Django 6.0.2 on 2026-04-26 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pore_analysis', '0009_remove_analysispricingrate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunPodQueueMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('queue_name', models.CharField(max_length=100, unique=True)),
                ('pod_id', models.CharField(max_length=100, unique=True)),
                ('pod_name', models.CharField(blank=True, default='', max_length=200)),
                ('endpoint_url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': 'RunPod Queue Mapping',
                'verbose_name_plural': 'RunPod Queue Mappings',
                'ordering': ['queue_name'],
            },
        ),
    ]
